// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAMotosMVC.Data;

#nullable disable

namespace SAMotosMVC.Migrations
{
    [DbContext(typeof(SAMotosMVCContext))]
    partial class SAMotosMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAMotosMVC.Models.SAMoto", b =>
                {
                    b.Property<int>("idSAMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSAMoto"));

                    b.Property<int>("SAcilindraje")
                        .HasColumnType("int");

                    b.Property<string>("SAcolor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAmarca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAmodelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSAMoto");

                    b.ToTable("SAMoto");
                });
#pragma warning restore 612, 618
        }
    }
}
